#!/bin/bash

package=neofetch

sudo pacman -S $package >> package_install_results.log
# >> is called redirect, that is append the output of
# a command to a file

if [ $? -eq 0 ]
then
    echo "The installation of $package was successful."
    echo "The new command is available here:"
    which $package
else
    echo "$package failed to install."
fi
