#!/bin/bash


finished=0

while [ $finished -ne 1 ]
do
    echo "What is your favourite Linux distribution?"

    echo "1 - Arch"
    echo "2 - CentOS"
    echo "3 - Debian"
    echo "4 - Mint"
    echo "5 - Ubuntu"
    echo "6 - Something else..."
    echo "7 - Exit the script."

    read distro;
    # reading input from the user via stdin

    case $distro in
        1) echo "Arch is a rolling release.";;
        2) echo "CentOS is popular on servers.";;
        3) echo "Debian is a community distribution.";;
        4) echo "Mint is popular on desktops and laptops.";;
        5) echo "Ubuntu is popular on both servers and computers.";;
        6) echo "There are many distributions out there.";;
        7) finished=1;;
        *) echo "You didn't enter an appropriate choice."
        # * is for catchall and is for any case that is not in the options
        # there have to be ;; at the end of each case statement, it can be on the other line
        #   with the exception of the last case option
    esac
done

echo "Thank you for using the script."
