#!/bin/bash



mynum=200

if [ ! $mynum -eq 200 ]
then
    echo "The condition is true."
else
    echo "The variable does not equal 300."
fi

# bashically don't repeate yourself unless you have to
# -ne can be used to explicitally say not equals to
# -gt stands for greater than
