#!/bin/bash
# Unvirsal update script
# /usr/local/bin repository is the one where all the scripts and executables are located



release_file=/etc/os-release

if grep -q "Arch" $release_file
then
    sudo pacman -Syu
fi

if grep -q "Ubuntu" $release_file || grep -q "Debian" $release_file
then
    sudo apt update
    sudo apt dist-upgrade
fi

