#!/bin/bash

# for scheduling jobs/scripts, we require 'at'.
logfile=job_results.log

echo "The script ran at the following time: $(date)" > $logfile
# atd not running error message. need to look into it
# that was because of atd (at deamon) not running in the background
# systemctl enable atq solves it
# use man at for more information

