#!/bin/bash

# arrays in shell

# 0 indexed array in bash
array_name=("element1" "element2" "element3" "element4") 

# Bashically dictionary in shell
declare -A arr_name=(["key1"]="value1" ["key2"]="value2" ["key2"]="value2") 

