#!/bin/bash

# data streams
#   stdout --> output of any successfull command
#   stderr --> output of echo $? on a failed command
find /etc -type f
# there are some failed commands also in the ouput
# that is because some files and folders require sudo

find /etc -type f 2> /dev/null
# -------------------------------------------------------------
# /dev/null is a blackhole in linux file system.
# anything that is moved or copied into it is never seen from, nor heard from again
# -------------------------------------------------------------
# here we are redirecting any output that has stderr to /dev/null



# ........ n> /dev/null
# n=2 --> stderr
# n=1 --> stdout
# n=nothing --> bydefault implies 1




# stdout is everyting that is printed to the screen and is not an error
# stderr is everyting that is printed to the screen and is an error
# stdout is designated by n=1
# stderr is designated by n=2

# > overwrite a file
# >> append to a file



find -type f &> file.txt
# & represents both stderr and stdout

find -type f 1> stdout.txt 2> stderr.txt
# split the stdout and stderr
# can also be written as follows
find /etc -type f > stdout.txt 2>&1
# here we are saying that redirect the output of the command to
# a file named stdout.txt (overwrite to it) and also redirect the stderr
# to the same place where the stdout is going









