#!/bin/bash
# Update script

release_file=/etc/os-release
logfile=/var/log/updater.log
errorlog=/var/log/updater_errors.log

if grep -q "Arch" $release_file
then
    # the host is based on Arch, run the pacman update command
    sudo pacman -Syu 1>$logfile 2>$errorlog

    if [ $? -ne 0 ]
    then
        echo "An error occured, please check the $errorlog file."
    fi
fi


if grep -q "Pop" $release_file || grep -q "Ubuntu" $release_file
then
    # the host is based on Ubuntu
    # run the apt version of the command

    sudo apt update 1>$logfile 2>$errorlog
    sudo apt dist-upgrade

    if [ $? -ne 0 ]
    then
        echo "An error occured, please check the $errorlog file."
    fi
fi
