#!/bin/bash

ls -lh $1
# you might want to give in an argument to a script to maybe backup
# some data to some script

lines=$(ls -lh $1 | wc -l)



# t=$(($lines - 1))
# echo "You have $t objects inside the $1 directory."

echo "You have $(($lines - 1)) objects inside the $1 directory."
# these both work the same way
# head and tail are used to display the top and bottom respectively
