#!/bin/bash

# Check to make suer the user has entered excatly two arguments

if [ $# -ne 2 ]
then
    echo "Usage: backup.sh <source_directory> <target_directory>"
    echo "Pleae try again."
    exit 1
fi

# Check to see if rsync is installed.
if ! command -v rsync > /dev/null 2>&1
then
    echo "This script requires rsync to be installed."
    echo "Please use your distribution's package manager to install rsync and try again"
    exit 2
    # try having distinct exit codes
fi

# Capture the current date, and store it in the format YYYY-MM-DD
current_date=$(date +%Y-%m-%d)
rsync_options="-avb --backup-dir $2/current_date --delete " # --dry-run
# these are the flags to the rsync command
# the --dry-run flag shows you what would happen if you run a command without changing anything
$(which rsync) $rsync_options $1 $2/current >> backup_$current_date.log
# the which rsync command makes the script more portable and independent of the system
# if making changes to the main dir, then the rerun of the backup script will only
# recopy those files that either were not there or have a different modification time as compared
